const leftTitles = [
    'Abounding',
    'Accomplished',
    'Accurate',
    'Active',
    'Adolescent',
    'Aggressive',
    'Ancient',
    'Anonymous',
    'Apprentice',
    'Art-School',
    'Aspiring',
    'At-Capacity',
    'Atmospheric',
    'Autonomous',
    'Avaricious',
    'Bait-Snatching',
    'Basement',
    'Buried',
    'Carefree',
    'Careful',
    'Caretaking',
    'Casual',
    'Catchable',
    'Celebratory',
    'Change-it-Up',
    'Clever',
    'Cliffhanging',
    'Comparative',
    'Competant',
    'Connected',
    'Covetous',
    'Cowardly',
    'Crafty',
    'Creative',
    'Crisp',
    'Curious',
    'Dad-Joking',
    'Detailed',
    'Detailed-Oriented',
    'Digital-Age',
    'Disconnected',
    'Discovered',
    'Down-And-Out',
    'Dreamy',
    'Easy-breezy',
    'Eco-friendly',
    'Efficient',
    'Emergent',
    'Emerging',
    'Energetic',
    'Fickle',
    'Fierce',
    'Flapping',
    'Flightless',
    'Flower-Loving',
    'Flying',
    'Freshly Delivered',
    'Friendly',
    'Friendship',
    'Full-fledged',
    'Future',
    'Glittering',
    'Global',
    'Gorgeous',
    'Greedy',
    'Greenhouse',
    'Handmade',
    'Happy',
    'Hay-Feverish',
    'Heavenly',
    'Herbivorous',
    'Highly Aware',
    'Hip',
    'History-Loving',
    'Hobby-Level',
    'Home',
    'Homey',
    'Hooked',
    'Hospitable',
    'Humming',
    'Inexperienced',
    'Interior',
    'Internet',
    'Invested',
    'Invulnerable',
    'Jovial',
    'Kindly',
    'Knowledge-Thirsty',
    'Late-Night',
    'Legendary',
    'Liberal-Arts',
    'Lonely',
    'Lucky',
    'Ludicrously Popular',
    'Materialistic',
    'Mature',
    'Messy',
    'Mistakenly Caught',
    'Moderate',
    'Night-Owl',
    'Nook Inc.\'s',
    'Novice',
    'Occasional',
    'Omnivorous',
    'One-Room',
    'Organic',
    'Outdoor-Loving',
    'Outdoorsy',
    'Overacting',
    'Overboard',
    'Overnight',
    'Over-Shelled',
    'Overstuffed',
    'Partially Obscured',
    'Photogenic',
    'Plucky',
    'Polymorphing',
    'Pond-Raised',
    'Precocious',
    'Pro',
    'Rare',
    'Rascally',
    'Ready',
    'Refined',
    'Reliable',
    'Respected',
    'Responsible',
    'Restless',
    'Risen',
    'Rotten',
    'Rough-And-Tumble',
    'Rowdy',
    'Rumormongering',
    'Savvy',
    'Science-y',
    'Seashore',
    'Seasonal',
    'Second-Floor',
    'Self-paced',
    'Self-Possessed',
    'Shadowy',
    'Sharp',
    'Shell-Grabbing',
    'Shifty',
    'Single-Occupant',
    'Sleepless',
    'Small-Fry',
    'Smartphone',
    'So-Called',
    'Soothing',
    'Specific',
    'Sports-Minded',
    'Status-Minded',
    'Summer-Born',
    'Sweet-Smelling',
    'Swept-Away',
    'Teary-eyed',
    'Tentative',
    'Thorny',
    'Thrifty',
    'Tidal',
    'Tidy',
    'Total',
    'Trailblazing',
    'Trapped',
    'Traveling',
    'Trendy',
    'Trivia',
    'Tropically Grown',
    'Twin\'s',
    'Unabashedly',
    'Understated',
    'Unhindered',
    'Unique',
    'Unpearable',
    'Untamed',
    'Untossable',
    'Upstart',
    'Vigorous',
    'Water\'s Edge',
    'Waterway',
    'Wave-Tossed',
    'Weak',
    'Weekend',
    'Well-Known',
    'Widely Accepted',
    'Wide-Ranging',
    'Wild',
    'Wild-Child',
    'Wishful',
    'Worldwide'
];

const rightTitles = [
    'Adventurer',
    'Ally',
    'Angler',
    'Artisan',
    'Artist',
    'Authority',
    'Avatar',
    'Backbone',
    'Beach Bum',
    'Beast',
    'Beginner',
    'Bellionaire',
    'Bill Payer',
    'Birthday Boy/Girl',
    'Blossom',
    'Boss',
    'Bounty',
    'Boy/Girl',
    'Brute',
    'Buddy',
    'Bug Fan',
    'Caretaker',
    'Challenger',
    'Child',
    'Chill Soul',
    'Chiller',
    'Chum',
    'Cleaner',
    'Clown',
    'Club Member',
    'Coast Dweller',
    'Coconut',
    'Collector',
    'Connector',
    'Consumer',
    'Coordinator',
    'Creator',
    'Creature',
    'Crusher',
    'Crybaby',
    'Custodian',
    'Dancer',
    'Deadeye',
    'Decorating Fiend',
    'Defender',
    'Designer',
    'Dietitian',
    'Dreamer',
    'Eccentric',
    'Ecologist',
    'Egg',
    'Emperor/Empress',
    'Engineer',
    'Enthusiast',
    'Eventuality',
    'Family Member',
    'Father/Mother',
    'Figure',
    'Fish',
    'Fisher',
    'Fishing Fan',
    'Fixer',
    'Flag Waver',
    'Floaty Thing',
    'Flower',
    'Force',
    'Fossil',
    'Fowl',
    'Frenzy',
    'Freshman',
    'Friend',
    'Gardener',
    'Genius',
    'Ghost',
    'Groom/Birde',
    'Ground Traveler',
    'Grub',
    'Guard',
    'Hobbyist',
    'Hunter',
    'Influencer',
    'Insect',
    'Intellectual',
    'Interior-Design Fan',
    '"It" Guy/Girl',
    'Keeper',
    'Kind',
    'Klutz',
    'Lad/Lass',
    'Landlord',
    'Lawn Clippings',
    'Legend',
    'Life',
    'Life Hacker',
    'Life-Form',
    'Loner',
    'Manager',
    'Materlist',
    'Meanie',
    'Mermaid',
    'Meteorite',
    'Model',
    'Moneybags',
    'Mr./Ms. Popular',
    'Muscle',
    'Musician',
    'Music-Lover',
    'Neatnik',
    'Neophyte',
    'Observationist',
    'One',
    'Other Half',
    'Overachiever',
    'Pal',
    'Paradise',
    'Partier',
    'Partitioner',
    'Party Animal',
    'Patron',
    'Pear',
    'Person',
    'Personality',
    'Pesca Pro',
    'Phoenix',
    'Photographer',
    'Pioneer',
    'Poet',
    'Problem Solver',
    'Prodigy',
    'Producer',
    'Punk',
    'Pupa',
    'Reaction',
    'Reckless One',
    'Rejuvenator',
    'Remodeler',
    'Representative',
    'Researcher',
    'Resident',
    'Reviewer',
    'Ringleader',
    'Rookie',
    'Rose',
    'Runner',
    'Savant',
    'Scent',
    'Seashell Seller',
    'Season',
    'Seeker',
    'Semiprofessional',
    'Sentiment',
    'Shell Fan',
    'Shell Master',
    'Shellector',
    'Shopaholic',
    'Shy Kid',
    'Sidekick',
    'Slingshot Ace',
    'Sneezer',
    'Something or Other',
    'Sort',
    'Sorter',
    'Specialist',
    'Speculator',
    'Sprout',
    'Stalkholder',
    'Standard',
    'Star',
    'Student',
    'Stylist',
    'Sundries Fan',
    'Superstar',
    'Surfer',
    'Talent',
    'Tourist',
    'Trader',
    'Transformer',
    'Trash',
    'Traveler',
    'Tree',
    'Tropical Fish',
    'Troublemaker',
    'Truth',
    'Type',
    'Virtuoso',
    'Walking Dictionary',
    'Wallflower',
    'Wanderer',
    'Wild Child',
    'Worrywart',
    'Youngster'
];

export {leftTitles, rightTitles};